<?php

namespace App\Http\Requests\Admin\Group;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title'=> 'nullable|string',
            'shop_id'=> 'required|integer|exists:shops,id',
        ];
    }

    public function messages()
    {
        return [
        ]; // TODO: Change the autogenerated stub
    }
}
