<?php

namespace App\Http\Requests\Admin\Shop;

use Illuminate\Foundation\Http\FormRequest;

class UpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=> 'required|string',
            'contacts'=>'required|numeric',
            'address'=>'required|string',
        ];
    }

    public function messages()
    {
        return [
            'name.required'=>'Это поле необходимо заполнить',
            'name.string'=>'Это поле должно быть строкой',
        ]; // TODO: Change the autogenerated stub
    }
}
