<?php

namespace App\Http\Requests\Admin\Delivery;

use Illuminate\Foundation\Http\FormRequest;

class StoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'curator_id'=> 'required|exists:users,id',
            'shop_id'=> 'required|exists:users,id',
            'volunteer_id'=> 'required|exists:users,id',
            'ward_id'=> 'required|exists:users,id',
        ];
    }


    public function messages()
    {
        return [
        ]; // TODO: Change the autogenerated stub
    }
}
