<?php

namespace App\Http\Requests\Volunteer\Delivery;

use Illuminate\Foundation\Http\FormRequest;

class ProductRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required|string',
            'weight'=>'required|integer',
            'count'=>'required|integer',
            'expiration_date'=>'required|date',
            'cost'=>'required|integer'
        ];
    }


    public function messages()
    {
        return [
        ]; // TODO: Change the autogenerated stub
    }
}
